version: '3.9'
services:
  todo-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    tty: true  # コンテナ内で対話的にコマンド実行を可能にする